apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
  namespace: ica0022
  labels:
    app: ica0022-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: ica0022-app
  template:
    metadata:
      labels:
        app: ica0022-app
    spec:
      containers:
        - name: app
          image: ica0022:v1.1.0
          command: ["waitress-serve", "--listen=0.0.0.0:8080", "missing_module:app"]
          ports:
            - containerPort: 8080
          env:
            - name: DB_HOST
              value: db
            - name: DB_PORT
              value: "5432"
            - name: DB_NAME
              value: ica0022
            - name: DB_USER
              value: ica0022
            - name: DB_PASSWORD
              value: ica0022-pass